# This file has been generated by node2nix 1.5.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "accepts-1.3.4" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.4.tgz";
        sha1 = "86246758c7dd6d21a6474ff084a4740ec05eb21f";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "body-parser-1.18.2" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.18.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.18.2.tgz";
        sha1 = "87678a19d84b47d859b83199bd59bce222b10454";
      };
    };
    "bson-1.0.4" = {
      name = "bson";
      packageName = "bson";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bson/-/bson-1.0.4.tgz";
        sha1 = "93c10d39eaa5b58415cbc4052f3e53e562b0b72c";
      };
    };
    "bytes-3.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz";
        sha1 = "d32815404d689699f85a4ea4fa8755dd13a96048";
      };
    };
    "content-disposition-0.5.2" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.2.tgz";
        sha1 = "0cf68bb9ddf5f2be7961c3a85178cb85dba78cb4";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "1f4y61wc913jrnga7nny83gzf9l2488q6sl1ry9lbwgh5x5d3va0xcc0xrmjk6gdxl6d4r6rsk800xp5bazhjrx05yx1wpc8c8gg0w4";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "0q0fsr8bk1m83z0am0h2xn09vyfcf18adscxms8hclznwks1aihsisd96h8npx0idq5wwnypnqrkyk25m5d9zh3dk7rjs29nybc8bkc";
      };
    };
    "depd-1.1.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.1.tgz";
        sha1 = "5783b4e1c459f06fa5ca27f991f3d06e7a310359";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "express-4.16.2" = {
      name = "express";
      packageName = "express";
      version = "4.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.16.2.tgz";
        sha1 = "e35c6dfe2d64b7dca0a5cd4f21781be3299e076c";
      };
    };
    "express-validator-5.0.0" = {
      name = "express-validator";
      packageName = "express-validator";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/express-validator/-/express-validator-5.0.0.tgz";
        sha512 = "0d7xpyr8azjjlalznmw5sv90mfl05n6zj5qvfklm3hdf1ls60ljmgjrqvf92bjs63d43cc7yy35smj20ic0xyljvrsrr8scvz640gx9";
      };
    };
    "finalhandler-1.1.0" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.0.tgz";
        sha1 = "ce0b6855b45853e791b2fcc680046d88253dd7f5";
      };
    };
    "forwarded-0.1.2" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz";
        sha1 = "98c23dab1175657b8c0573e8ceccd91b0ff18c84";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "http-errors-1.6.2" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.2.tgz";
        sha1 = "0a002cc85707192a7e7946ceedc11155f60ec736";
      };
    };
    "iconv-lite-0.4.19" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.19.tgz";
        sha512 = "0jj1pdq3j9ak8cixn2kjp7ip8hf3xgnb85j4jr32yf9rry620v9072c0kk577mllfk1zl9wzs5ypwzbp7vbhf7j31d5rrqgwb0nldm1";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ipaddr.js-1.5.2" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.5.2.tgz";
        sha1 = "d4b505bde9946987ccf0fc58d9010ff9607e3fa0";
      };
    };
    "lodash-4.17.5" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.5.tgz";
        sha512 = "11hikgyas884mz8a58vyixaahxbpdwljdw4cb6qp15xa3sfqikp2mm6wgv41jsl34nzsv1hkx9kw3nwczvas5p73whirmaz4sxggwmj";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "mime-1.4.1" = {
      name = "mime";
      packageName = "mime";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.4.1.tgz";
        sha512 = "2sz22r1xrnyvq6jg0h6b6cab3s3xdsfqa0n6vl9xv9gq3ppcxrcpg2hqfc41xjwnfwfkr6240l5gys7nds61ch6xcb3gr3fwsl7x398";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "mongodb-3.0.2" = {
      name = "mongodb";
      packageName = "mongodb";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mongodb/-/mongodb-3.0.2.tgz";
        sha512 = "22ikj205iii3m8gk4ri6bvrsmvjgjvazs60d6la3qqamhvvry8w9kw3lvwl1vb1i1r1sq8hslgni0w23vrbixk9i901cwlhjjd0b78k";
      };
    };
    "mongodb-core-3.0.2" = {
      name = "mongodb-core";
      packageName = "mongodb-core";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mongodb-core/-/mongodb-core-3.0.2.tgz";
        sha512 = "00c9rffzgn5jahcn6vcrppziny56fq8nnl5fgfib93mjck4yjjbwk5pa7m6mlqnh4l6mf6cgrlhm7r6rrx2cig9sj10wlsh06mp8l57";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "proxy-addr-2.0.2" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.2.tgz";
        sha1 = "6571504f47bb988ec8180253f85dd7e14952bdec";
      };
    };
    "qs-6.5.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.1.tgz";
        sha512 = "3waqapyj1k4g135sgj636rmswiaixq19is1rw0rpv4qp6k7dl0a9nwy06m7yl5lbdk9p6xpwwngnggbzlzaz6rh11c86j2nvnnf273r";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "raw-body-2.3.2" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.3.2.tgz";
        sha1 = "bcd60c77d3eb93cde0050295c3f379389bc88f89";
      };
    };
    "require_optional-1.0.1" = {
      name = "require_optional";
      packageName = "require_optional";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require_optional/-/require_optional-1.0.1.tgz";
        sha512 = "3r4zhpy8dg2wg13rg8msjhpm4vp58ind0lvfgwccqb4jiaa3b80w0gs139dk361zvg244fzzggrmgih63bzrvzd063nb76ykv5ky4xa";
      };
    };
    "resolve-from-2.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-2.0.0.tgz";
        sha1 = "9480ab20e94ffa1d9e80a804c7ea147611966b57";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "semver-5.5.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.5.0.tgz";
        sha512 = "0h32zh035y8m6dzcqhcymbhwgmc8839fa1hhj0jfh9ivp9kmqfj1sbwnsnkzcn9qm3sqn38sa8ys2g4c638lpnmzjr0a0qndmv7f8p1";
      };
    };
    "send-0.16.1" = {
      name = "send";
      packageName = "send";
      version = "0.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.16.1.tgz";
        sha512 = "3c9rfxzsayrnka50s3hdbln9sjzad94ll4z2nx83i3rqciy4dxj05x34sjmm64k46zmk99pj8g4bcwk476a3iqzpcxgja28s8jqnl0j";
      };
    };
    "serve-static-1.13.1" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.13.1.tgz";
        sha512 = "2ahchxbzy0wr61gjy85p35cx4rkfb5347fmglk5rb2wawla3nhx6xx8hsgvmvjcsp5vfdilvf84kcnvp832f1anylsg4sqgpdk188w5";
      };
    };
    "setprototypeof-1.0.3" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.3.tgz";
        sha1 = "66567e37043eeb4f04d91bd658c0cbefb55b8e04";
      };
    };
    "setprototypeof-1.1.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz";
        sha512 = "2jlhhawfqdiga1m6if01ks1q3yx56k5vj6wf372589vkswvdflw7224viivxali56b0jjsckpmjy10rj6fcakhw2dbq2psr197kzw86";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "statuses-1.3.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.3.1.tgz";
        sha1 = "faf51b9eb74aaef3b3acf4ad5f61abf24cb7b93e";
      };
    };
    "type-is-1.6.15" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.15.tgz";
        sha1 = "cab10fb4909e441c82842eafe1ad646c81804410";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha1 = "9f95710f50a267947b2ccc124741c1028427e713";
      };
    };
    "validator-9.4.0" = {
      name = "validator";
      packageName = "validator";
      version = "9.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-9.4.0.tgz";
        sha512 = "20c0w5vm0y1s1nsirs7j8d1hl38vhr69sbnz84vf44h7p96l8n14vyfq581kycn4qclppkx0wwcykkvlc2bnhmmr6fv27pvkxi05nby";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
  };
  args = {
    name = "zipcodeservice";
    packageName = "zipcodeservice";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."accepts-1.3.4"
      sources."array-flatten-1.1.1"
      (sources."body-parser-1.18.2" // {
        dependencies = [
          sources."setprototypeof-1.0.3"
        ];
      })
      sources."bson-1.0.4"
      sources."bytes-3.0.0"
      sources."content-disposition-0.5.2"
      sources."content-type-1.0.4"
      sources."cookie-0.3.1"
      sources."cookie-signature-1.0.6"
      sources."debug-2.6.9"
      sources."depd-1.1.2"
      sources."destroy-1.0.4"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      sources."express-4.16.2"
      sources."express-validator-5.0.0"
      sources."finalhandler-1.1.0"
      sources."forwarded-0.1.2"
      sources."fresh-0.5.2"
      (sources."http-errors-1.6.2" // {
        dependencies = [
          sources."depd-1.1.1"
        ];
      })
      sources."iconv-lite-0.4.19"
      sources."inherits-2.0.3"
      sources."ipaddr.js-1.5.2"
      sources."lodash-4.17.5"
      sources."media-typer-0.3.0"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      sources."mime-1.4.1"
      sources."mime-db-1.30.0"
      sources."mime-types-2.1.17"
      sources."mongodb-3.0.2"
      sources."mongodb-core-3.0.2"
      sources."ms-2.0.0"
      sources."negotiator-0.6.1"
      sources."on-finished-2.3.0"
      sources."parseurl-1.3.2"
      sources."path-to-regexp-0.1.7"
      sources."proxy-addr-2.0.2"
      sources."qs-6.5.1"
      sources."range-parser-1.2.0"
      sources."raw-body-2.3.2"
      sources."require_optional-1.0.1"
      sources."resolve-from-2.0.0"
      sources."safe-buffer-5.1.1"
      sources."semver-5.5.0"
      sources."send-0.16.1"
      sources."serve-static-1.13.1"
      sources."setprototypeof-1.1.0"
      sources."slasp-0.0.4"
      sources."statuses-1.3.1"
      sources."type-is-1.6.15"
      sources."unpipe-1.0.0"
      sources."utils-merge-1.0.1"
      sources."validator-9.4.0"
      sources."vary-1.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "REST API interface providing access to the zipcode data set";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}