# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "express-4.15.2" = {
      name = "express";
      packageName = "express";
      version = "4.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.15.2.tgz";
        sha1 = "af107fc148504457f2dca9a6f2571d7129b97b35";
      };
    };
    "express-validator-2.18.0" = {
      name = "express-validator";
      packageName = "express-validator";
      version = "2.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/express-validator/-/express-validator-2.18.0.tgz";
        sha1 = "d65d252b6355d7dfe935180463370d8915357dad";
      };
    };
    "mongodb-2.0.55" = {
      name = "mongodb";
      packageName = "mongodb";
      version = "2.0.55";
      src = fetchurl {
        url = "https://registry.npmjs.org/mongodb/-/mongodb-2.0.55.tgz";
        sha1 = "a09dd77259f6bba69f7dd592a011c11aa5761097";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "accepts-1.3.3" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz";
        sha1 = "c3ca7434938648c3e0d9c1e328dd68b622c284ca";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "content-disposition-0.5.2" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.2.tgz";
        sha1 = "0cf68bb9ddf5f2be7961c3a85178cb85dba78cb4";
      };
    };
    "content-type-1.0.2" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.2.tgz";
        sha1 = "b7d113aee7a8dd27bd21133c4dc2529df1721eed";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "debug-2.6.1" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.1.tgz";
        sha1 = "79855090ba2c4e3115cc7d8769491d58f0491351";
      };
    };
    "depd-1.1.0" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.0.tgz";
        sha1 = "e1bd82c6aab6ced965b97b88b17ed3e528ca18c3";
      };
    };
    "encodeurl-1.0.1" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.1.tgz";
        sha1 = "79e3d58655346909fe6f0f45a5de68103b294d20";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.8.0" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.0.tgz";
        sha1 = "6f631aef336d6c46362b51764044ce216be3c051";
      };
    };
    "finalhandler-1.0.1" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.0.1.tgz";
        sha1 = "bcd15d1689c0e5ed729b6f7f541a6df984117db8";
      };
    };
    "fresh-0.5.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.0.tgz";
        sha1 = "f474ca5e6a9246d6fd8e0953cfa9b9c805afa78e";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "parseurl-1.3.1" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz";
        sha1 = "c8ab8c9223ba34888aa64a297b28853bec18da56";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "proxy-addr-1.1.4" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.1.4.tgz";
        sha1 = "27e545f6960a44a627d9b44467e35c1b6b4ce2f3";
      };
    };
    "qs-6.4.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.4.0.tgz";
        sha1 = "13e26d28ad6b0ffaa91312cd3bf708ed351e7233";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "send-0.15.1" = {
      name = "send";
      packageName = "send";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.15.1.tgz";
        sha1 = "8a02354c26e6f5cca700065f5f0cdeba90ec7b5f";
      };
    };
    "serve-static-1.12.1" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.12.1.tgz";
        sha1 = "7443a965e3ced647aceb5639fa06bf4d1bbe0039";
      };
    };
    "setprototypeof-1.0.3" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.3.tgz";
        sha1 = "66567e37043eeb4f04d91bd658c0cbefb55b8e04";
      };
    };
    "statuses-1.3.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.3.1.tgz";
        sha1 = "faf51b9eb74aaef3b3acf4ad5f61abf24cb7b93e";
      };
    };
    "type-is-1.6.15" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.15.tgz";
        sha1 = "cab10fb4909e441c82842eafe1ad646c81804410";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "vary-1.1.1" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.1.tgz";
        sha1 = "67535ebb694c1d52257457984665323f587e8d37";
      };
    };
    "mime-types-2.1.15" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.15.tgz";
        sha1 = "a4ebf5064094569237b8cf70046776d09fc92aed";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "mime-db-1.27.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.27.0.tgz";
        sha1 = "820f572296bbd20ec25ed55e5b5de869e5436eb1";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "debug-2.6.3" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.3.tgz";
        sha1 = "0f7eb8c30965ec08c72accfa0130c8b79984141d";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "forwarded-0.1.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz";
        sha1 = "19ef9874c4ae1c297bcf078fde63a09b66a84363";
      };
    };
    "ipaddr.js-1.3.0" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.3.0.tgz";
        sha1 = "1e03a52fdad83a8bbb2b25cbf4998b4cffcd3dec";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "http-errors-1.6.1" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.1.tgz";
        sha1 = "5f8b8ed98aca545656bf572997387f904a722257";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "bluebird-2.11.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz";
        sha1 = "534b9033c022c9579c56ba3b3e5a5caafbb650e1";
      };
    };
    "lodash-3.10.1" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz";
        sha1 = "5bf45e8e49ba4189e17d482789dfd15bd140b7b6";
      };
    };
    "validator-4.2.1" = {
      name = "validator";
      packageName = "validator";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-4.2.1.tgz";
        sha1 = "c4a8316242e515cd784171986296f8f81fc2ab35";
      };
    };
    "mongodb-core-1.2.31" = {
      name = "mongodb-core";
      packageName = "mongodb-core";
      version = "1.2.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/mongodb-core/-/mongodb-core-1.2.31.tgz";
        sha1 = "f1e6405f03d40846fdb838a702507affa3cb2c39";
      };
    };
    "readable-stream-1.0.31" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.31.tgz";
        sha1 = "8f2502e0bc9e3b0da1b94520aabb4e2603ecafae";
      };
    };
    "es6-promise-2.1.1" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-2.1.1.tgz";
        sha1 = "03e8f3c7297928e5478d6ab1d0643251507bdedd";
      };
    };
    "bson-0.4.23" = {
      name = "bson";
      packageName = "bson";
      version = "0.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/bson/-/bson-0.4.23.tgz";
        sha1 = "e65a2e3c7507ffade4109bc7575a76e50f8da915";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
  };
  args = {
    name = "roomservice";
    packageName = "roomservice";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      (sources."express-4.15.2" // {
        dependencies = [
          (sources."accepts-1.3.3" // {
            dependencies = [
              (sources."mime-types-2.1.15" // {
                dependencies = [
                  sources."mime-db-1.27.0"
                ];
              })
              sources."negotiator-0.6.1"
            ];
          })
          sources."array-flatten-1.1.1"
          sources."content-disposition-0.5.2"
          sources."content-type-1.0.2"
          sources."cookie-0.3.1"
          sources."cookie-signature-1.0.6"
          (sources."debug-2.6.1" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          sources."depd-1.1.0"
          sources."encodeurl-1.0.1"
          sources."escape-html-1.0.3"
          sources."etag-1.8.0"
          (sources."finalhandler-1.0.1" // {
            dependencies = [
              (sources."debug-2.6.3" // {
                dependencies = [
                  sources."ms-0.7.2"
                ];
              })
              sources."unpipe-1.0.0"
            ];
          })
          sources."fresh-0.5.0"
          sources."merge-descriptors-1.0.1"
          sources."methods-1.1.2"
          (sources."on-finished-2.3.0" // {
            dependencies = [
              sources."ee-first-1.1.1"
            ];
          })
          sources."parseurl-1.3.1"
          sources."path-to-regexp-0.1.7"
          (sources."proxy-addr-1.1.4" // {
            dependencies = [
              sources."forwarded-0.1.0"
              sources."ipaddr.js-1.3.0"
            ];
          })
          sources."qs-6.4.0"
          sources."range-parser-1.2.0"
          (sources."send-0.15.1" // {
            dependencies = [
              sources."destroy-1.0.4"
              (sources."http-errors-1.6.1" // {
                dependencies = [
                  sources."inherits-2.0.3"
                ];
              })
              sources."mime-1.3.4"
              sources."ms-0.7.2"
            ];
          })
          sources."serve-static-1.12.1"
          sources."setprototypeof-1.0.3"
          sources."statuses-1.3.1"
          (sources."type-is-1.6.15" // {
            dependencies = [
              sources."media-typer-0.3.0"
              (sources."mime-types-2.1.15" // {
                dependencies = [
                  sources."mime-db-1.27.0"
                ];
              })
            ];
          })
          sources."utils-merge-1.0.0"
          sources."vary-1.1.1"
        ];
      })
      (sources."express-validator-2.18.0" // {
        dependencies = [
          sources."bluebird-2.11.0"
          sources."lodash-3.10.1"
          sources."validator-4.2.1"
        ];
      })
      (sources."mongodb-2.0.55" // {
        dependencies = [
          (sources."mongodb-core-1.2.31" // {
            dependencies = [
              sources."bson-0.4.23"
            ];
          })
          (sources."readable-stream-1.0.31" // {
            dependencies = [
              sources."core-util-is-1.0.2"
              sources."isarray-0.0.1"
              sources."string_decoder-0.10.31"
              sources."inherits-2.0.3"
            ];
          })
          sources."es6-promise-2.1.1"
        ];
      })
      sources."slasp-0.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "REST API interface providing access to the rooms data set";
      license = "MIT";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}